name: "SpotlightBeta-Patchworks"
app: "12368503"
consumer_key: "2aZzmhzrNsXqjQcDv0z3eB8cQ"
consumer_secret: "qBHKHCoaHOsfrzkTB5AchtWgpB1wCIuQBc6ZMQlylod5QdAdkk"
access_token_key: ""
access_token_secret: ""
defaultSearchResultCount: 15